server:
  port: 8001
  contextPath:
  servlet:
      sesssion:
        timeout: 86400


app:
  ads:
    adsence:
      head: private/adsence_head.code
      top: private/adsence_top.code
      bottom: private/adsence_bottom.code
    yandex:
      main_page: private/yandex_main_page.code
      top: private/yandex_top.code
      bottom: private/yandex_bottom.code

telegram:
  bot:
    enabled: true
    name: bvn13_blog_test_bot
    channel: bvn13_blog_test
    token_file: private/telegram_bot_test.token
    master_name : bvn13
    proxy:
      host:
      port:
      username:
      password:
      type:


spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jade4j:
    caching: false

  dataSource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog
    username: blog
    password: blogpass

  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hbm2ddl.auto: update
    show_sql: true
    use_sql_comments: true
    format_sql: true

  redis:
    host: localhost
    port: 6379
    default_expire_time: 86400


  session:
    store-type: redis

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

